# Generated by Django 3.1.5 on 2021-02-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_casillero', models.TextField(blank=True, max_length=100, verbose_name='num_casillero')),
                ('estado', models.TextField(blank=True, max_length=100, verbose_name='estado')),
                ('fecha', models.DateField(blank=True, max_length=100, verbose_name='fecha')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='email')),
            ],
        ),
    ]
