# Generated by Django 3.1.5 on 2021-02-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='fecha',
            field=models.DateField(max_length=100, verbose_name='fecha'),
        ),
    ]
