# Generated by Django 3.1.5 on 2021-02-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_auto_20210202_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='fecha',
        ),
    ]
